name = "blueprint-gen-example"
defaultTargets = ["Example"]

[[require]]
name = "blueprint-gen"
git = "https://github.com/hanwenzhu/blueprint-gen"
rev = "main"

[[require]]
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.25.0-rc2"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls"

[[lean_lib]]
name = "Example"
